apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:9c897d277a3126ba384c1aae4722990c66ed52d0
        ports:
        - containerPort: 80
