apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:cdac9d7894b938062b9da081a9683b9233f0a4c6
        ports:
        - containerPort: 80
