apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 065967698410.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:df309a81ad3a1dbde46172d72a94f20ec53ab90a
        ports:
        - containerPort: 80
