apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 065967698410.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:eb475bd97519e4f0756ec044a514b3ce2c60b742
        ports:
        - containerPort: 80
