apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 065967698410.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:e6d3df3c41ea9c80bfed5c41f0380e68e35b92f7
        ports:
        - containerPort: 80
